In [ ]:
import numpy as np

ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(ar)


numpy.ndarray

In [ ]:
ar*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
import numpy as np

aa = np.array([[10,20,30,40],[50,60,70,80]])



array([[ 30,  60,  90, 120],
       [150, 180, 210, 240]])

In [ ]:
len(aa)  #배열의 크기 구하기

2

In [ ]:
len(aa[0])

4

In [ ]:
aa.shape  

(2, 4)

In [ ]:
aa>=40

array([[False, False, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
#인덱싱
#리스트의 인덱싱과 같은 방식으로 사용
#다차원 배열은 콤마(,)를 사용하여 접근

#1차원 배열 인덱싱
a = np.array([0,1,2,3,4])
#print(a[2],a[-1])

#다차원 배열
a  = np.array([[0,1,2],[3,4,5]])
print(a)
print(a[0,0], a[0,1],a[-1,-1])

[[0 1 2]
 [3 4 5]]
0 1 5


In [ ]:
#슬라이싱
#복수 개의 원소를 인덱싱하는 것을 의미

a = np.array([[0,1,2,3],[4,5,6,7,]])
print(a)
a[0, :]                   # ':'은 모두를 의미

[[0 1 2 3]
 [4 5 6 7]]


array([0, 1, 2, 3])

In [ ]:
a[:,1]

array([1, 5])

In [ ]:
a[1,1:2] 

array([5])

In [ ]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
#이 행렬에서 값 7 을 인덱싱한다
print(m[1,2])
# 이 행렬에서 값 14을 인덱싱한다
print(m[2,4])
# 이 행렬에서 배열 [6,7]을 슬라이싱한다
print(m[1,1:3])
#이 행렬에서 배열 [7, 12] 을 슬라이싱한다
print(m[1:3,2])
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다
print(m[0:2,3:5])

In [ ]:
# 배열 인덱싱
#배열의 대괄호 안에 위치 정보를 나타내는 새로운 배열 입력 가능
#이 새로운 배열을 인덱스 배열이라고 함
# 인덱스 배열에는 불리언 배열과 정수배열의 두 가지가 존재
#불리언 배열 방식
# - TRUE, False의 두 값으로만 구성
# - 인덱스 배열의 크기가 기존배열의 크기와 같아야함
#정수 배열 방식
# - 기존 배열의 원소를 가리키는 정수값으로 인덱스 배열이 구성됨
# - 기존 배열과 크기가 달라도 가능(중복도 가능)

In [ ]:
import numpy as np

a = np.array ([0, 1, 2, 3, 4, 5, 6, 7, 8,9])
idx = np.array([True,False,True,False,True,
                False,True,False,True,False])

a[idx]

array([0, 2, 4, 6, 8])

In [ ]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])