In [ ]:
# 차원 축소 연산
# - 1차원 배열에 대해 평균을 구하면 상수 값(0차원)이 반환됨
# - 2차원 배열에서 각 열에 대한 평균을 구하면 1차원 배열이 반환됨
#     분류      |           명령어
#   최대/최소   :     min, max, argmin, argmax
#   통계 관련   :     sum, mean, median, std, var
#  불리언 관련  :     all, any     

In [ ]:
import numpy as np
# 1차원 배열 예시
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [ ]:
# 합계
x.sum()

10

In [ ]:
# 최솟값
x.min()

1

In [ ]:
# 최대값
x.max()

4

In [ ]:
# 배열에서 최솟값의 위치
x.argmin()

0

In [ ]:
# 배열에서 최대값의 위치
x.argmax()

3

In [ ]:
np.median(x)

2.5

In [ ]:
np.any([True, True, False])

In [ ]:
z = np.array([4,7,3,34,8,10,-5,1,99])
z

array([ 4,  7,  3, 34,  8, 10, -5,  1, 99])

In [ ]:
z.sum()

161

In [ ]:
z.min()

-5

In [ ]:
z.max()

99

In [ ]:
z.argmin()

6

In [ ]:
z.argmax()

8

In [ ]:
# mean은 평균이고, median은 중간값입니다.
b = np.array([1,2,3,7,9])
b

array([1, 2, 3, 7, 9])

In [ ]:
b.mean()

4.4

In [ ]:
np.median(b)

3.0

In [ ]:
# OR
np.any([True, True, False])

True

In [ ]:
# AND
np.all([True, True, False])

False

In [ ]:
np.all([True, True])

True

In [ ]:
np.any([False, False])

False

In [ ]:
# 파이썬에서 list 자료형의 모든 항목이 참이라면 True를 반환해주는
# all 함수와 적어도 하나의 항목이 참이라면 True를 반환해주는 any 함수가 있습니다.
# 이 함수들은 논리연산에 유용하게 사용할 수 있습니다.

In [ ]:
all([True, 1, {3}])

True

In [ ]:
all([True, 1, {}]) # {}는 거짓을 의미하기 때문

False

In [ ]:
any([True, 1, {}])

True

In [ ]:
all({}) # 거짓인 항목이 없기 때문에

True

In [ ]:
any([]) # 참인 항목이 없기 때문에

False

In [ ]:
# 차원 축소 연산
a = np.zeros((100, 100), dtype=np.int)
a[0][0] = 1
a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.any(a != 0)

True

In [ ]:
np.all(a == a)

True

In [ ]:
a = np.array([9,9,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a <= b) & (b <= c)).all()

False

In [ ]:
# 차원 축소 연산
# - 2차원 배열에 차원 축소 연산을 적용할 때에는 계산 차원을 지정해 주어야 함
# - axis 인수를 사용하여 지정
# - axis = 0 인 경우 열 연산, axis = 1인 경우 행 연산

In [ ]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum()

6

In [ ]:
x.sum(axis=0)

array([3, 3])

In [ ]:
x.sum(axis=1)

array([2, 4])

In [ ]:
ee = np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
ee

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# 전체의 최댓값
ee.max()

12

In [ ]:
# 각 행의 합
ee.sum(axis=1)

array([10, 26, 42])

In [ ]:
# 각 행의 최댓값
ee.max(axis=1)

array([ 4,  8, 12])

In [ ]:
# 각 열의 평균
ee.mean(axis=0)

array([5., 6., 7., 8.])

In [ ]:
# 각 열의 최솟값
ee.min(axis=0)

array([1, 2, 3, 4])