In [ ]:
import numpy as np
# 배열의 크기 구분
# - 같은 값과 같은 숫자를 가진 배열이라도 크기가 다르면
#   다른 배열
# - 배열의 연산 및 반복에서 주의 요망
#   예 : 길이가 5일 1차원 배열, (5,1)인 2차원배열,
#        (1, 5)인 2차원 배열
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [ ]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# 아래와 같은 행렬을 만든다. (float16, 이름 bb)
# 10 20 30 40
# 50 60 70 80
import numpy as np
bb = np.array([[10,20,30,40], [50,60,70,80]], dtype = 'float16')
bb

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]], dtype=float16)

In [ ]:
# 1. int16의 같은 행렬을 만드시오. (이름 cc)
cc = np.array([[10,20,30,40], [50,60,70,80]], dtype = 'int16')
cc

array([[10, 20, 30, 40],
       [50, 60, 70, 80]], dtype=int16)

In [ ]:
# 2. flatten을 사용하여 1차원으로 변형시킨다.
cc.flatten()

array([10, 20, 30, 40, 50, 60, 70, 80], dtype=int16)

In [ ]:
# 3. cc 행렬을 (4X2) 크기로 변형시킨다.
#    1) reshape을 사용하여 변형
cc.reshape(4, 2) # or cc.reshape(4, -1)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]], dtype=int16)

In [ ]:
#    2) 전치를 사용하여 변형
cc.T

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]], dtype=int16)

In [ ]:
# 4. cc와 같은 크기를 가진, 원소를
#    1로만 가지는 행렬 생성 (이름 dd)
dd = np.ones_like(cc)
dd

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
# 4. cc와 같은 크기를 가진, 원소를
#    0로만 가지는 행렬 생성 (이름 ff)
ff = np.zeros_like(cc)
ff

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [ ]:
# 배열의 연결
# hstack : 행의 수가 같은 배열을 옆으로 연결 (horizontal)
a1 = np.ones((2, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [ ]:
# vstack : 열의 수가 같은 배열을 아래위로 연결 (vertical)
b1 = np.ones((2, 3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# dstack : 행과 열이 아닌 깊이 방향으로 배열을 연결
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.dstack([c1, c2])
(np.dstack([c1, c2])).shape

(3, 4, 2)

In [ ]:
# stack : 앞의 dstack 메소드의 확장 기능 제공
# axis 인수(기본 값 0)를 지정하여 지정한 인수로 차원을 확장
# axis = 0 : 위에서 아래로 Data를 합친다는 의미
c = np.stack([c1, c2])   # axis = 0 으로 기본 세팅
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
c.shape

(2, 3, 4)

In [ ]:
# axis = 1 : 좌에서 우로 데이터를 합친다는 의미
c = np.stack([c1, c2], axis=1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [ ]:
c.shape

(3, 2, 4)

In [ ]:
# tile : 동일한 배열을 반복하여 연결
a = np.array([[0,1,2], [3,4,5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
# 1.  hstack 사용
c1 = np.array([[1, 4], [2, 5], [3,6],[1, 4], [2, 5], [3,6]])
np.hstack([c1, c1])

array([[1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6],
       [1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6]])

In [ ]:
# 2. vstack 사용
c2 = np.array([[1,4,1,4], [2,5,2,5], [3,6,3,6]])
np.vstack([c2, c2])

array([[1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6],
       [1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6]])

In [ ]:
# 3. tile 사용
ee = np.array([[1, 4], [2, 5], [3, 6]])
np.tile(ee, (2, 2))

array([[1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6],
       [1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6]])

In [ ]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

# 셀 시간 측정 매직 명령어
%time
z = np.zeros_like(x)
for i in range(10000):
  z[i] = x[i] + y[i]

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.87 µs


In [ ]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [ ]:
%%time
z = x + y

CPU times: user 49 µs, sys: 4 µs, total: 53 µs
Wall time: 57.5 µs


In [ ]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [ ]:
# 백터화 연산
# -> Numpy의 배열은 벡터화 연산(vectorized operation)을 지원함
#   - 배열간의 연산에서 요소들끼리(element-wise) 연산
#   - 일반 연산에서 각 요소에 모두 적용
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a + b

array([5, 4, 5, 8])

In [ ]:
a == b  # 논리 연산도 가능

array([False,  True, False,  True])

In [ ]:
np.all(a == b)
# all 명령 사용 시 모든 원소가 같은 지 검사한 후
# 결과를 True/False 로 반환

False

In [ ]:
# 모든 요소 적용되는 일반 연산
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
10 ** a

array([    1,    10,   100,  1000, 10000])

In [ ]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
100 * a

array([  0, 100, 200, 300, 400])

In [ ]:
# 브로드캐스팅
# - 서로 다른 크기의 두 배열의 사칙연산을 자동으로 수행하는 기능
# - 크기가 큰 배열에 맞추어 크기가 작은 배열을 확장하여 수행
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [ ]:
x + y

array([1, 2, 3, 4, 5])

In [ ]:
x + 1

array([1, 2, 3, 4, 5])

In [ ]:
#x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x = np.array([[0, 1, 2],
              [1, 2, 3],
              [2, 3, 4],
              [3, 4, 5],
              [4, 5, 6]])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])