In [ ]:
import numpy as np
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
answer = []
for di in ar:
    answer.append(2 *di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
ar*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
import numpy as np
a =np.array ([1, 2, 3])
b =np.array ([10, 20,30])
a * 2 + b

array([12, 24, 36])

In [ ]:
a == 3

array([False, False,  True])

In [ ]:
b < 20

array([ True, False, False])

In [ ]:
(a == 2) & (b > 10)

array([False,  True, False])

In [ ]:
import numpy as np
c =np.array ([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
len(c)

2

In [ ]:
len(c[0])

3

In [ ]:
d =np.array ([[[1, 2, 3,4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]],
             [[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]]])
len(d), len (d[0]), len (d[0][0])

(2, 3, 4)

In [ ]:
# a =np.array ([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [ ]:
# c =np.array ([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [ ]:
d =np.array ([[[1, 2, 3,4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]],
             [[11, 12, 13, 14],
              [15, 16, 17, 18],
              [19, 20, 21, 22]]])

In [ ]:
aa=np.array([[10,20,30,40],[50,60,70,80,]])
aa*3

array([[ 30,  60,  90, 120],
       [150, 180, 210, 240]])

In [ ]:
len(aa)
print(aa.ndim)
print(aa.shape)

2
(2, 4)


In [ ]:
aa>40

array([[False, False, False, False],
       [ True,  True,  True,  True]])